# 기본 정보 설정
title: "조수현 블로그"  # 블로그 제목
description: "AI 서비스 개발"  # 블로그 설명
url: "https://ssuhyon.github.io/"  # 블로그의 기본 URL (루트 도메인)
baseurl: ""  # 블로그가 호스팅되는 서브 디렉토리 경로

# 작성자 정보
author:
  name: "Jo Suhyeon"  # 작성자의 이름
  email: "josuhyeon@icloud.com"  # 작성자의 이메일 주소

# 플러그인 설정
plugins:
  - jekyll-feed       # RSS 피드를 생성하는 플러그인
  - jekyll-paginate   # 페이지를 나누는 기능을 제공하는 플러그인
  - jekyll-sitemap    # 사이트맵을 자동으로 생성하는 플러그인
  - jekyll-archives   # 카테고리 및 태그별 아카이브를 생성하는 플러그인

# jekyll-archives 설정
jekyll-archives:
  enabled:
    - categories  # 카테고리별 아카이브 생성을 활성화
  layouts:
    category: category  # 카테고리별 아카이브에 사용할 레이아웃 파일 지정
  permalinks:
    category: /category/:name/  # 카테고리 아카이브의 URL 구조 지정

# 페이지네이션 설정
paginate: 8 # 한 페이지에 표시할 포스트 수
paginate_path: "/page:num" # 페이징 경로 설정

# CSS 추가 설정
sass:
  style: expanded  # SASS 컴파일 스타일을 사람이 읽기 쉬운 expanded 형식으로 설정

# 빌드에서 제외할 파일
exclude:
  - README.md  # Jekyll 빌드 과정에서 제외할 파일 목록 (README.md 제외)
